### ISSUE TITLE
The player does not work

### ISSUE THREAD

**Issue by emreyildirim99** [ozankaraali/PiTV#4]
Hi, the channels are listed after login, but when I click on one of the channels, the video player always spins and it does not play the stream. I tried both on MacOS & Windows and have the same problem.

**Comment by ozankaraali** [comment]
Hello, I am aware of the bug, I hope I will check it in my free time, thank you for the interest.

**Comment by ozankaraali** [comment]
Hello, sorry for the very late response. I just had the motivation and time to rebuild it. Currently I believe with the 1.0.3-beta1, I have solved the errors. If you still interested, I suggest you to try the binaries on: https://github.com/ozankaraali/PiTV/releases/tag/latest , if not, thanks for your contribution and time and sorry for really really late response. If you encounter any errors, feel free to reopen an issue. Cheers.
