### ISSUE TITLE
deb package ubuntu mate 20.04 settings seems to be locked

### ISSUE THREAD

**Issue by skaox** [ozankaraali/PiTV#9]
Hi,
when starting Pitv in terminal :
```
pitv 
(node:2247128) UnhandledPromiseRejectionWarning: Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/pitv/resources/app/.webpack/main/native_modules/build/Release/classic_level.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at 4583 (/usr/lib/pitv/resources/app/.webpack/main/index.js:2:46600)
    at o (/usr/lib/pitv/resources/app/.webpack/main/index.js:2:901278)
(Use `pitv --trace-warnings ...` to show where the warning was created)
(node:2247128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[2247158:1220/043020.718079:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[2247128:1220/043025.897828:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018
```

Settings seems to be blocked
![Screenshot](https://user-images.githubusercontent.com/22966700/208611435-392e5493-bab7-47af-919a-76a7a22ffbec.png)

System is Ubuntu Mate 20.04.5

Possible to use local m3u playlists !?

Thank you in advance.

**Comment by ozankaraali** [comment]
It seems like my Ubuntu buildbot doesn't have all dependencies already, I will try to resolve it later. Meanwhile, you can try to build in your computer by git clone, yarn, yarn make (or yarn start for development), if you have time and want to run it as soon as possible, probably if you have glibcxx (reference: https://stackoverflow.com/a/70990697).

I have planned to use local m3u playlists but have not yet implemented it, I thought it would be enough to use online playlists, thanks for the feedback, and I will add it as a priority.

**Comment by ozankaraali** [comment]
Hi again @skaox, sorry for the late response. I have tried to fix that issue at: https://github.com/ozankaraali/PiTV/releases/tag/latest
I still don't have a Linux OS to try, if you're still interested, can you try that and let me know? Thanks!

**Comment by skaox** [comment]
Hi, I confirm the problem is corrected.

![1](https://user-images.githubusercontent.com/22966700/210294220-bc423314-6190-41fd-a09c-3e5ff8b1e757.png)


If I delete default playlist https://iptv-org..../index.m3u blank page but after closing and reopening pitv the list is still there :

![2](https://user-images.githubusercontent.com/22966700/210294092-739d96dc-f7be-4d51-a0aa-337a26ae84a3.png)

if I try to read a channel of that list (same problem with all channels) error :

![3](https://user-images.githubusercontent.com/22966700/210294564-7984e0a2-8dc8-4788-ab9c-619d759e9abc.png)

I will wait until it's possible to use local m3u file

Thank you

**Comment by skaox** [comment]
Hello, I confirm the problem is corrected.

![1](https://user-images.githubusercontent.com/22966700/210294220-bc423314-6190-41fd-a09c-3e5ff8b1e757.png)


If I delete default playlist https://iptv-org.../index.m3u blank page no more settings button but after closing and reopening pitv everything (list and settings button) came back :

![2](https://user-images.githubusercontent.com/22966700/210294092-739d96dc-f7be-4d51-a0aa-337a26ae84a3.png)

All channels I've tried on that list give me this error :

![3](https://user-images.githubusercontent.com/22966700/210294564-7984e0a2-8dc8-4788-ab9c-619d759e9abc.png)

I'll wait for doing more tests until it's possible to use local m3u file.

Thank you !

**Comment by devtestmrx** [comment]
All channels I've tried on that list give me this error :
![Screenshot from 2024-06-04 08-37-01](https://github.com/ozankaraali/PiTV/assets/171061200/a491e417-2a09-40fa-b6b9-89e8473eb5d4)

**Comment by ozankaraali** [comment]
I don’t know, I don’t use Linux but AFAIK it packs ffmpeg correctly. If you see the default iptv-org playlist runs videos correctly, may it be your provider?
